spring.datasource.url=jdbc:postgresql://localhost:5432/postingAdvertisements
spring.datasource.username=advertisements
spring.datasource.password=advertisements
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# Tomcat configuration
server.tomcat.max-http-form-post-size=50MB
server.tomcat.max-swallow-size=50MB
server.tomcat.max-connections=10000
server.tomcat.connection-timeout=60000
server.tomcat.max-keep-alive-requests=100

# Multipart configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.location=${java.io.tmpdir}
spring.servlet.multipart.resolve-lazily=true

# ???????? ??? ???????
logging.level.org.springframework.web=DEBUG
logging.level.org.apache.coyote=DEBUG

image.avatars.dir=images/avatars/
image.ads.dir=images/ads/
image.base.url=/images
server.address=0.0.0.0

server.tomcat.basedir=${java.io.tmpdir}
server.servlet.context-parameters.tomcat.util.http.fileupload.disk.DiskFileItem.delete-request-files=true
